(lang dune 3.18)

(name handlebars-ml)

(generate_opam_files true)

(source
 (github nikochiko/handlebars-ml))

(authors "Kaustubh M <ktvm42@gmail.com>")

(maintainers "Kaustubh M <ktvm42@gmail.com>")

(license MIT)

(documentation https://url/to/documentation)

(package
 (name handlebars-ml)
 (synopsis "Handlebars templating for OCaml")
 (description "A longer description")
 (depends ocaml
          (sedlex (>= 3.6)))
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
